package org.lugge.scripts.osrs.luckyisland.task.SuperState;

import org.lugge.scripts.osrs.luckyisland.data.Island.IslandItems;
import org.lugge.scripts.osrs.luckyisland.data.Island.IslandNPCs;
import org.lugge.scripts.osrs.luckyisland.data.Island.IslandObstacles;
import org.lugge.scripts.osrs.luckyisland.data.Island.IslandOre;
import org.lugge.scripts.osrs.luckyisland.task.Island.IslandActions;
import org.lugge.scripts.osrs.luckyisland.task.Island.IslandConditions;
import org.powerbot.script.rt4.ClientAccessor;
import org.powerbot.script.rt4.ClientContext;
import org.powerbot.script.rt4.Game;

public class SuperStatedActions extends ClientAccessor{
    public SuperStatedActions(ClientContext ctx) {
        super(ctx);
    }

    IslandConditions IslandConditions = new IslandConditions(ctx);
    IslandActions IslandActions = new IslandActions(ctx);

    public void doIsland(){
        switch (IslandConditions.getIslandState()) {
            case RANDOMISE_LOOK: IslandActions.randomiseLook();
                break;
            case TALK_RUNESCAPE_GUIDE: IslandActions.talkNPC(IslandNPCs.RUNESCAPE_GUIDE);
                break;
            case CLICK_WRENCH: IslandActions.openTab(Game.Tab.OPTIONS);
                break;
            case OPEN_RUNESCAPE_GUIDE_DOOR: IslandActions.passObstacle(IslandObstacles.RUNESCAPE_GUIDE_DOOR);
                break;
            case WALK_SURVIVAL_EXPERT: IslandActions.walkNPC(IslandNPCs.SURVIVAL_EXPERT);
                break;
            case TALK_SURVIVAL_EXPERT: IslandActions.talkNPC(IslandNPCs.SURVIVAL_EXPERT);
                break;
            case CLICK_INVENTORY: IslandActions.openTab(Game.Tab.INVENTORY);
                break;
            case CUT_LOGS: IslandActions.cutLogs();
                break;
            case LITE_FIRE: IslandActions.liteFire();
                break;
            case CLICK_SKILLS: IslandActions.openTab(Game.Tab.STATS);
                break;
            case FISH_FISH: IslandActions.fishFish();
                break;
            case COOK_FISH: IslandActions.cockFish();
                break;
            case WALK_SURVIVAL_EXPERT_GATE: IslandActions.traverseToObstacle(IslandObstacles.SURVIVAL_EXPERT_GATE);
                break;
            case OPEN_SURVIVAL_EXPERT_GATE: IslandActions.passObstacle(IslandObstacles.SURVIVAL_EXPERT_GATE);
                break;
            case WALK_MASTER_CHEF: IslandActions.traverseToObstacle(IslandObstacles.MASTER_CHEF_DOOR1);
                break;
            case OPEN_MASTER_CHEF_DOOR1: IslandActions.passObstacle(IslandObstacles.MASTER_CHEF_DOOR1);
                break;
            case TALK_MASTER_CHEF: IslandActions.talkNPC(IslandNPCs.MASTER_CHEF);
                break;
            case MIX_INGREDIENTS: IslandActions.mixIngredients();
                break;
            case USE_RANGE: IslandActions.useRange();
                break;
            case CLICK_HARP: IslandActions.openTab(Game.Tab.MUSIC);
                break;
            case OPEN_MASTER_CHEF_DOOR2: IslandActions.passObstacle(IslandObstacles.MASTER_CHEF_DOOR2);
                break;
            case CLICK_EMOTES: IslandActions.openTab(Game.Tab.EMOTES);
                break;
            case DO_EMOTE: IslandActions.doEmote();
                break;
            case ACTIVATE_RUNNING: IslandActions.activateRunning();
                break;
            case WALK_QUEST_GUIDE: IslandActions.traverseToObstacle(IslandObstacles.QUEST_GUIDE_DOOR);
                break;
            case OPEN_QUEST_GUIDE_DOOR: IslandActions.passObstacle(IslandObstacles.QUEST_GUIDE_DOOR);
                break;
            case TALK_QUEST_GUIDE: IslandActions.talkNPC(IslandNPCs.QUEST_GUIDE);
                break;
            case CLICK_QUESTS: IslandActions.openTab(Game.Tab.QUESTS);
                break;
            case CLIMB_QUEST_GUIDE_LADDER: IslandActions.passObstacle(IslandObstacles.QUEST_GUIDE_LADDER);
                break;
            case WALK_MINING_INSTRUCTOR: IslandActions.walkNPC(IslandNPCs.MINING_INSTRUCTOR);
                break;
            case TALK_MINING_INSTRUCTOR: IslandActions.talkNPC(IslandNPCs.MINING_INSTRUCTOR);
                break;
            case INSPECT_TIN: IslandActions.inspectRock(IslandOre.TIN);
                break;
            case INSPECT_COPPER: IslandActions.inspectRock(IslandOre.COPPER);
                break;
            case MINE_TIN: IslandActions.mineRock(IslandOre.TIN);
                break;
            case MINE_COPPER: IslandActions.mineRock(IslandOre.COPPER);
                break;
            case SMELT_BRONZE: IslandActions.smeltBronze();
                break;
            case USE_ANVIL: IslandActions.useAnvil();
                break;
            case SMITH_DAGGER: IslandActions.smithDagger();
                break;
            case WALK_MINING_INSTRUCTOR_GATE: IslandActions.traverseToObstacle(IslandObstacles.MINING_INSTRUCTOR_GATE);
                break;
            case OPEN_MINING_INSTRUCTOR_GATE: IslandActions.passObstacle(IslandObstacles.MINING_INSTRUCTOR_GATE);
                break;
            case WALK_COMBAT_INSTRUCTOR: IslandActions.walkNPC(IslandNPCs.COMBAT_INSTRUCTOR);
                break;
            case TALK_COMBAT_INSTRUCTOR: IslandActions.talkNPC(IslandNPCs.COMBAT_INSTRUCTOR);
                break;
            case CLICK_EQUIPMENT: IslandActions.openTab(Game.Tab.EQUIPMENT);
                break;
            case OPEN_EQUIPMENT: IslandActions.openEquipment();
                break;
            case EQUIP_DAGGER: IslandActions.equipItem(IslandItems.DAGGER);
                break;
            case CLOSE_EQUIPMENT: IslandActions.closeEquipment();
                break;
            case EQUIP_MELEE: IslandActions.equipItem(IslandItems.SWORD_AND_SHIELD);
                break;
            case CLICK_COMBAT: IslandActions.openTab(Game.Tab.ATTACK);
                break;
            case WALK_RAT_GATE: IslandActions.traverseToObstacle(IslandObstacles.RAT_GATE);
                break;
            case OPEN_RAT_GATE: IslandActions.passObstacle(IslandObstacles.RAT_GATE);
                break;
            case ATTACK_RAT: IslandActions.attackNPC(IslandNPCs.RAT);
                break;
            case EQUIP_RANGE: IslandActions.equipItem(IslandItems.BOW_AND_ARROWS);
                break;
            case WALK_COMBAT_INSTRUCTOR_LADDER: IslandActions.traverseToObstacle(IslandObstacles.COMBAT_INSTRUCTOR_LADDER);
                break;
            case CLIMB_COMBAT_INSTRUCTOR_LADDER: IslandActions.passObstacle(IslandObstacles.COMBAT_INSTRUCTOR_LADDER);
                break;
            case WALK_BANKER: IslandActions.walkNPC(IslandNPCs.BANKER);
                break;
            case TALK_BANKER: IslandActions.talkNPC(IslandNPCs.BANKER);
                break;
            case CLOSE_BANK: IslandActions.closeBank();
                break;
            case USE_POLL_BOOTH: IslandActions.usePollBooth();
                break;
            case CLOSE_POLL_BOOTH: IslandActions.closePollBooth();
                break;
            case OPEN_BANK_DOOR: IslandActions.passObstacle(IslandObstacles.BANK_DOOR);
                break;
            case TALK_FINANCIAL_ADVISOR: IslandActions.talkNPC(IslandNPCs.FINANCIAL_INSTRUCTOR);
                break;
            case OPEN_FINANCIAL_ADVISOR_DOOR: IslandActions.passObstacle(IslandObstacles.FINANCIAL_ADVISOR_DOOR);
                break;
            case WALK_BROTHER_BRACE: IslandActions.traverseToObstacle(IslandObstacles.BROTHER_BRACE_DOOR1);
                break;
            case OPEN_BROTHER_BRACE_DOOR1: IslandActions.passObstacle(IslandObstacles.BROTHER_BRACE_DOOR1);
                break;
            case TALK_BROTHER_BRACE: IslandActions.talkNPC(IslandNPCs.BROTHER_BRACE);
                break;
            case CLICK_PRAYER: IslandActions.openTab(Game.Tab.PRAYER);
                break;
            case CLICK_FRIENDS_LIST: IslandActions.openTab(Game.Tab.FRIENDS_LIST);
                break;
            case CLICK_IGNORE_LIST: IslandActions.openTab(Game.Tab.IGNORED_LIST);
                break;
            case OPEN_BROTHER_BRACE_DOOR2: IslandActions.passObstacle(IslandObstacles.BROTHER_BRACE_DOOR2);
                break;
            case WALK_MAGIC_INSTRUCTOR: IslandActions.walkNPC(IslandNPCs.MAGIC_INSTRUCTOR);
                break;
            case TALK_MAGIC_INSTRUCTOR: IslandActions.talkNPC(IslandNPCs.MAGIC_INSTRUCTOR);
                break;
            case CLICK_MAGE_BOOK: IslandActions.openTab(Game.Tab.MAGIC);
                break;
            case SELECT_AIR_STRIKE: IslandActions.selectAirStrike();
                break;
            case ATTACK_CHICKEN: IslandActions.attackNPC(IslandNPCs.CHICKEN);
                break;
        }
    }
}
